version: '3.8'

services:
  graphql_inspector:
    build: .
    container_name: graphql_inspector
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    networks:
      - secnet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  secnet:
    driver: bridge