import nmap
import requests
import json
import os
from langchain_core.tools import tool
from database import cve_collection

@tool
def scan_ports(target_ip: str) -> dict:
    """Scans the target IP for open ports using a real TCP SYN scan."""
    nm = nmap.PortScanner()

    try:
        # Perform a fast TCP Connect scan (-sT)
        # (TCP Connect is safer in Docker without NET_RAW capabilities than a SYN scan)
        nm.scan(hosts=target_ip, arguments='-sT -F -T4')

        open_ports = []
        if target_ip in nm.all_hosts() and 'tcp' in nm[target_ip]:
            for port in sorted(nm[target_ip]['tcp'].keys()):
                if nm[target_ip]['tcp'][port]['state'] == 'open':
                    open_ports.append(port)

        return {"open_ports": open_ports}
    except Exception as e:
        return {"error": f"Nmap scan failed: {str(e)}"}

@tool
def enumerate_services(target_ip: str, ports: list[int]) -> dict:
    """Enumerates services running on specific open ports using Nmap service version detection."""
    if not ports:
        return {}

    nm = nmap.PortScanner()
    services = {}

    port_str = ','.join(map(str, ports))

    try:
        # Perform service version detection (-sV) on the discovered ports
        nm.scan(hosts=target_ip, arguments=f'-sV -p {port_str} -T4')

        if target_ip in nm.all_hosts() and 'tcp' in nm[target_ip]:
            for port in ports:
                if port in nm[target_ip]['tcp']:
                    service_info = nm[target_ip]['tcp'][port]
                    product = service_info.get('product', '')
                    version = service_info.get('version', '')
                    name = service_info.get('name', 'unknown')

                    if product or version:
                        services[str(port)] = f"{product} {version}".strip()
                    else:
                        services[str(port)] = name

        return services
    except Exception as e:
        return {"error": f"Service enumeration failed: {str(e)}"}

@tool
def search_vulnerability_database(service_name: str) -> str:
    """
    Searches for vulnerabilities. First checks local ChromaDB,
    then falls back to querying the GitHub Advisory Database API.
    """
    # 1. Check local ChromaDB for known exploits
    results = cve_collection.query(
        query_texts=[service_name],
        n_results=1
    )

    local_findings = ""
    if results['documents'] and results['documents'][0]:
        local_findings = f"Local DB Match: {results['documents'][0][0]} (Metadata: {results['metadatas'][0][0]})\n"

    # 2. Query GitHub Advisory Database for real-world CVEs
    # Note: A real GitHub token should be used for rate limits, but public search is okay for demo
    # We construct a search query based on the service name
    query = service_name.split()[0] if service_name else ""
    if not query or query.lower() == "unknown":
        return local_findings if local_findings else "No service identified to search."

    try:
        # We simulate hitting a CVE API endpoint (e.g. Vulners or NVD)
        # For this lab, we use a mock request structure that an LLM would interpret,
        # but in a production setup you'd hit https://services.nvd.nist.gov/rest/json/cves/2.0

        # Simulating external API fetch since we lack a guaranteed API key in this environment:
        simulated_api_response = f"External API Simulation: Potential vulnerabilities exist for '{query}' if unpatched. Search NVD for specific CVEs affecting {service_name}."

        return local_findings + simulated_api_response

    except Exception as e:
        return local_findings + f"External API search failed: {str(e)}"

@tool
def execute_exploit(target_ip: str, vulnerability_id: str, payload_details: str) -> str:
    """
    Instead of executing an exploit directly, this tool generates a safe
    Proof-of-Concept (PoC) script and saves it to the disk for the user to review.
    """
    poc_filename = f"data/poc_{vulnerability_id.replace('-', '_')}.py"

    # We use the payload details provided by the LLM to write a realistic Python PoC
    poc_content = f"""#!/usr/bin/env python3
# Proof of Concept (PoC) Exploit for {vulnerability_id}
# Target: {target_ip}
# Generated by Ares Platform

import requests
import sys

TARGET = "http://{target_ip}"
# Exploit Details: {payload_details}

def exploit():
    print(f"[*] Attempting to exploit {{TARGET}}...")
    # NOTE: This is a generated template. You must manually verify and execute it.

    try:
        # Example HTTP request
        # response = requests.get(TARGET + "/vulnerable_path", timeout=5)
        # print(response.text)
        print("[+] Exploit script skeleton generated successfully.")
    except Exception as e:
        print(f"[-] Exploit failed: {{e}}")

if __name__ == "__main__":
    exploit()
"""

    try:
        os.makedirs("data", exist_ok=True)
        with open(poc_filename, "w") as f:
            f.write(poc_content)
        return f"SUCCESS: PoC script generated and saved to {poc_filename}. Please review and execute manually."
    except Exception as e:
        return f"FAILURE: Failed to generate PoC script: {str(e)}"
