version: '3.8'

services:
  api-shadow-hunter:
    build: .
    container_name: api_shadow_hunter
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./app:/app/app # For local development auto-reload

networks:
  internal:
    driver: bridge
