import argparse
import sys
import os

from .generator import generate_yara_rule

def main():
    parser = argparse.ArgumentParser(
        description="Auto-generates a YARA rule by analyzing a file's metadata and strings."
    )
    parser.add_argument(
        "input_file",
        help="Path to the file to analyze (binary or text)."
    )
    parser.add_argument(
        "-n", "--name",
        help="Name of the YARA rule to generate (must be a valid identifier).",
        default="AutoGeneratedRule"
    )
    parser.add_argument(
        "-o", "--output",
        help="Path to save the generated YARA rule. If not provided, prints to stdout."
    )
    parser.add_argument(
        "-a", "--author",
        help="Author name to include in the rule metadata.",
        default="AutoGenerator"
    )

    args = parser.parse_args()

    if not os.path.isfile(args.input_file):
        print(f"Error: Input file '{args.input_file}' not found or is not a file.", file=sys.stderr)
        sys.exit(1)

    # Validate rule name (simplified check: alphanumeric and underscores only, cannot start with a digit)
    if not args.name.isidentifier():
        print(f"Error: Rule name '{args.name}' is not a valid identifier. Use alphanumeric characters and underscores.", file=sys.stderr)
        sys.exit(1)

    try:
        with open(args.input_file, "rb") as f:
            data = f.read()

        file_name = os.path.basename(args.input_file)

        rule = generate_yara_rule(
            rule_name=args.name,
            data=data,
            file_name=file_name,
            author=args.author
        )

        if args.output:
            with open(args.output, "w", encoding="utf-8") as out_f:
                out_f.write(rule)
            print(f"Successfully generated rule and saved to {args.output}")
        else:
            print(rule)

    except PermissionError:
        print(f"Error: Permission denied when accessing '{args.input_file}'.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
